/**
 * @file agent.js
 * @description AI agent routes: a Gemini-backed query endpoint (with function
 * calling) and a deterministic auto-analysis endpoint.
 * @module routes/agent
 */

import express from "express";
import { GEMINI_MODEL, INPUT_LIMITS } from "../config.js";
import { authMiddleware, isValidString } from "../auth.js";
import { stadiumState } from "../state.js";
import {
  ai,
  agentTools,
  executeToolCall,
  generateFallbackResponse,
  buildSystemPrompt,
} from "../ai.js";

const router = express.Router();

// --- AI Agent Endpoint (Gemini with Function Calling) ---
/**
 * POST /api/agent/query
 *
 * Purpose: Query the AI Agent (Gemini) about stadium status or command options.
 * Authentication: Bearer JWT token required in Authorization header.
 * Request Body Shape:
 *   - message {string} - The question or command for the AI agent.
 * Response JSON (200 OK):
 *   - response {string} - Text response generated by Gemini.
 *   - toolsUsed {Array} - List of tool calls triggered during execution.
 *   - timestamp {number} - Epoch millisecond timestamp of the execution.
 * Response JSON (400 Bad Request / 500 Internal Server Error):
 *   - error {string} - Error description.
 *   - details {string} - Detailed error message (for 500 errors).
 *   - fallback {string} - A static markdown fallback response (for 500/unconfigured Gemini errors).
 * Status Codes:
 *   - 200 OK: AI agent successfully processed query.
 *   - 400 Bad Request: Missing query message.
 *   - 401 Unauthorized: Invalid or missing token.
 *   - 500 Internal Server Error: API or model execution failed (includes static fallback in response).
 */
router.post("/api/agent/query", authMiddleware, async (req, res) => {
  const { message } = req.body;

  // Reject empty, non-string, or oversized prompts before calling the model.
  if (!isValidString(message, INPUT_LIMITS.MESSAGE)) {
    return res.status(400).json({ error: "Message is required" });
  }

  if (!ai) {
    return res.status(500).json({
      error: "Gemini API key not configured",
      fallback: generateFallbackResponse(message),
    });
  }

  try {
    const systemPrompt = buildSystemPrompt(stadiumState);

    const toolDeclarations = agentTools.map((t) => ({
      name: t.name,
      description: t.description,
      parameters: t.parameters,
    }));

    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: [{ role: "user", parts: [{ text: message }] }],
      config: {
        systemInstruction: systemPrompt,
        tools: [{ functionDeclarations: toolDeclarations }],
        temperature: 0.3,
        maxOutputTokens: 2048,
      },
    });

    let resultText = "";
    let toolResults = [];
    let candidate = response.candidates?.[0];
    let parts = candidate?.content?.parts || [];

    // Process any function calls (tool executions) requested by the AI model
    const functionCalls = parts.filter((p) => p.functionCall);
    if (functionCalls.length > 0) {
      const toolOutputs = [];

      // Iterate through each requested tool call and execute it locally
      for (const fc of functionCalls) {
        const result = executeToolCall(fc.functionCall.name, fc.functionCall.args || {});
        toolOutputs.push({
          toolName: fc.functionCall.name,
          args: fc.functionCall.args,
          result,
        });
        toolResults.push({ tool: fc.functionCall.name, result });
      }

      // Structure the execution results into functionResponse parts for the model
      const functionResponses = functionCalls.map((fc, i) => ({
        functionResponse: {
          name: fc.functionCall.name,
          response: toolOutputs[i].result,
        },
      }));

      // Make a follow-up call to the model, passing the entire conversation history:
      // 1. Original user query
      // 2. Model's initial response (containing the function calls)
      // 3. The actual function response outputs
      const followUp = await ai.models.generateContent({
        model: GEMINI_MODEL,
        contents: [
          { role: "user", parts: [{ text: message }] },
          { role: "model", parts },
          { role: "user", parts: functionResponses },
        ],
        config: {
          systemInstruction: systemPrompt,
          temperature: 0.3,
          maxOutputTokens: 2048,
        },
      });

      const followParts = followUp.candidates?.[0]?.content?.parts || [];
      resultText = followParts.map((p) => p.text || "").join("\n");
    } else {
      resultText = parts.map((p) => p.text || "").join("\n");
    }

    res.json({
      response: resultText,
      toolsUsed: toolResults,
      timestamp: Date.now(),
    });
  } catch (error) {
    console.error("Gemini API error:", error);
    res.status(500).json({
      error: "AI processing error",
      details: error.message,
      fallback: generateFallbackResponse(message),
    });
  }
});

// --- AI Auto-Analysis Endpoint ---
/**
 * GET /api/agent/auto-analyze
 *
 * Purpose: Scans stadium state to produce risk assessment and recommended actions.
 * Request Parameters: None.
 * Request Body Shape: None.
 * Response JSON (200 OK):
 *   - overallRisk {string} - Evaluated risk level ("low", "medium", "high").
 *   - criticalZones {Array} - List of zones exceeding density thresholds.
 *   - congestedGates {Array} - List of gates with long queues.
 *   - activeIncidentCount {number} - Number of current active incidents.
 *   - recommendations {Array} - List of action items.
 *   - timestamp {number} - Epoch millisecond timestamp of the analysis.
 * Status Codes:
 *   - 200 OK: Analysis completed successfully.
 */
router.get("/api/agent/auto-analyze", async (_req, res) => {
  const criticalZones = Object.entries(stadiumState.zones)
    .filter(([_, z]) => z.riskLevel === "critical" || z.riskLevel === "high")
    .map(([name, z]) => `${name}: ${(z.density * 100).toFixed(0)}% density (${z.riskLevel})`);

  const congestedGates = Object.entries(stadiumState.gates)
    .filter(([_, g]) => g.queueLength > 50)
    .map(([name, g]) => `${name}: queue ${g.queueLength}`);

  const activeIncidents = stadiumState.incidents.filter((i) => i.status === "active");

  const analysis = {
    overallRisk: criticalZones.length > 0 ? "high" : congestedGates.length > 2 ? "medium" : "low",
    criticalZones,
    congestedGates,
    activeIncidentCount: activeIncidents.length,
    recommendations: [],
    timestamp: Date.now(),
  };

  if (criticalZones.length > 0) {
    analysis.recommendations.push("URGENT: Activate crowd control protocol for critical zones");
  }
  if (congestedGates.length > 0) {
    analysis.recommendations.push(
      `Reroute traffic from congested gates: ${congestedGates.map((g) => g.split(":")[0]).join(", ")}`
    );
  }
  if (
    stadiumState.weatherCondition.includes("rain") ||
    stadiumState.weatherCondition.includes("storm")
  ) {
    analysis.recommendations.push("Weather alert: Consider activating weather shelter protocol");
  }
  if (activeIncidents.length > 3) {
    analysis.recommendations.push(
      "Multiple active incidents detected. Consider escalating to security command."
    );
  }
  if (analysis.recommendations.length === 0) {
    analysis.recommendations.push("All systems nominal. Continue monitoring.");
  }

  res.json(analysis);
});

export default router;
